### ISSUE TITLE
Why are older crates.io versions being yanked?

### ISSUE THREAD

**Issue by nastevens** [KizzyCode/asn1_der-rust#2]
I noticed that all versions older than 0.6.2 have been yanked from crates.io. Is there a particular reason for this? Yanking is meant only to remove packages that have specific breaking issues: https://doc.rust-lang.org/cargo/reference/publishing.html#managing-a-cratesio-based-crate.

**Comment by KizzyCode** [comment]
I yanked the crates because they contain a [serious vulnerability](https://github.com/KizzyCode/asn1_der/issues/1) which allows you to crash the library by providing maliciously crafted input.

But I had not read the reference in a long time and my impression was that yanking is not only used for compile-breaking issues, but also for versions with serious vulnerabilities – I didn't know that this would also prevent the installation of depending packages (I thought yanking was only relevant for the development process).

I'll unyank the crates – but is there any way to mark them as insecure?

**Comment by nastevens** [comment]
I recommend filing a report with https://github.com/RustSec/advisory-db - that will alert users of the `cargo audit` tool to the vulnerability.

**Comment by dpc** [comment]
Advisory filled in `cargo-crev` https://github.com/dpc/crev-proofs/blob/bd26cb701a23dc056b50b542061f8173dbd91037/FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE/reviews/2019-06-packages-Ua7DxQ.proof.crev#L73
